// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCs1cI_pPN2ov5z4LKGBcuarUcm8jj0Plk',
    appId: '1:628924564823:web:3ffe0521c85ecdb7eb6a12',
    messagingSenderId: '628924564823',
    projectId: 'skill-link-5fdf3',
    authDomain: 'skill-link-5fdf3.firebaseapp.com',
    storageBucket: 'skill-link-5fdf3.firebasestorage.app',
    measurementId: 'G-ESG6RC80ZP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKtTyTL6TOMvc7ZXoPYIZnvNinlxExpLg',
    appId: '1:628924564823:android:cca8bfc7e45bbe61eb6a12',
    messagingSenderId: '628924564823',
    projectId: 'skill-link-5fdf3',
    storageBucket: 'skill-link-5fdf3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4frY-fBYjPEbde9bmPCf8wwIXpkLxYTQ',
    appId: '1:628924564823:ios:a383a6022767e5e7eb6a12',
    messagingSenderId: '628924564823',
    projectId: 'skill-link-5fdf3',
    storageBucket: 'skill-link-5fdf3.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4frY-fBYjPEbde9bmPCf8wwIXpkLxYTQ',
    appId: '1:628924564823:ios:a383a6022767e5e7eb6a12',
    messagingSenderId: '628924564823',
    projectId: 'skill-link-5fdf3',
    storageBucket: 'skill-link-5fdf3.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCs1cI_pPN2ov5z4LKGBcuarUcm8jj0Plk',
    appId: '1:628924564823:web:f04265cb4ff9aab2eb6a12',
    messagingSenderId: '628924564823',
    projectId: 'skill-link-5fdf3',
    authDomain: 'skill-link-5fdf3.firebaseapp.com',
    storageBucket: 'skill-link-5fdf3.firebasestorage.app',
    measurementId: 'G-MYKZ06233X',
  );
}
